### ISSUE TITLE
Error during send_notifications

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#117]
Cron emailed the following traceback on 2015-12-16 02:00:03 UTC:

    Traceback (most recent call last):                                                                                                                    
      File "/usr/local/aira/manage.py", line 11, in <module>                                                                     
        execute_from_command_line(sys.argv)                                                                                                     
      File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line                                                                                                                                            
        utility.execute()                                                                                                          
      File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)                                                                   
      File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
        self.execute(*args, **options.__dict__)                                                                         
      File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
        output = self.handle(*args, **options)                                                                            
      File "/usr/local/aira/aira/management/commands/send_notifications.py", line 29, in handle                                                   
        self.notify_user(user, user_agrifields, user)                                                                                            
      File "/usr/local/aira/aira/management/commands/send_notifications.py", line 59, in notify_user
        owner))                                                                                                                                
      File "/usr/local/aira/aira/management/commands/send_notifications.py", line 48, in get_email_context
        context['sd'] = agrifields[0].results.sd                                                                                                
      File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 160, in __getitem__
        return self._result_cache[k]                                                                                                              
    IndexError: list index out of range

**Comment by aptiko** [comment]
This was also sent on 18 and 20 December, but not in 17, 19 and 21.

**Comment by aptiko** [comment]
In addition, `loggertodb` on the same machine (megdobas), has given "list index out of range" on 2015-12-18 06:36 UTC and 2015-12-20 07:25 UTC. I don't know whether it is related. (This is likely a `pthelma` error and not an `aira` error. I'm not yet registering a bug at `pthelma`).

**Comment by aptiko** [comment]
Today I received a different message: django.utils.encoding.DjangoUnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 22: ordinal not in range(128).

```
Traceback (most recent call last):
  File "/usr/local/aira/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/aira/aira/management/commands/send_notifications.py", line 29, in handle
    self.notify_user(user, user_agrifields, user)
  File "/usr/local/aira/aira/management/commands/send_notifications.py", line 64, in notify_user
    html_message=msg_html)
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/mail/__init__.py", line 62, in send_mail
    return mail.send()
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 286, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 99, in send_messages
    sent = self._send(message)
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/mail/backends/smtp.py", line 113, in _send
    message = email_message.message()
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 254, in message
    msg['Subject'] = self.subject
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 200, in __setitem__
    name, val = forbid_multi_line_headers(name, val, self.encoding)
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/core/mail/message.py", line 85, in forbid_multi_line_headers
    val = force_text(val)
  File "/usr/local/aira-virtualenv/local/lib/python2.7/site-packages/django/utils/encoding.py", line 95, in force_text
    raise DjangoUnicodeDecodeError(s, *e.args)
django.utils.encoding.DjangoUnicodeDecodeError: 'ascii' codec can't decode byte 0xce in position 22: ordinal not in range(128). You passed in
<django.utils.functional.__proxy__ object at 0x7ff7b5fdb310> (<class 'django.utils.functional.__proxy__'>)
```

**Comment by kickapoo** [comment]
This error is more complex than it seems. Its associated with aira water balance model execution through celery tasks.

During debugging made the following steps or investigations:

Using the pure development instance of aira (meaning using sqlite3 as database), the management command `send notification` didn't run. Then `send notification` is executed  celery shell instance with `info` didn't produce any task queue/jobs (celery shell instance with `info` is  the command `celery -A aira worker -l info` and from now on I will refer it as `celery.aira.monitor`). 
 
Try to run the `send notification` line by line (using break points) :
/aira/management/commands/send_notifications.py, line 46
```python
for f in agrifields:
    f.results = email_users_response_data(f)
```
The `email_users_response_data(f)` is a mini wrapper from `aira.irma.main` to execute the model with celery.  The strange thing is that `f.results` will return a task instance but celery won't execute any tasks in `celery.aira.monitor`. 

Now using a sync database from production, the management command `send notification` of course didn't run and again no tasks are trigger to `celery.aira.monitor`. Running again the script line by line the  `email_users_response_data(f)`  didn't even produce a task instance. 
Also, try to bypass our `email_user_response_data(f)` with direct execution of the model through `aira.tasks.execute_model` or even `aira.calculate_agrifield`. The same as the above, no task will sent to celery workers. 

Stack a bit here, any suggestions will be great.

**Comment by kickapoo** [comment]
This is a follow up to my previous comment. 

First of all, the term `celery.aira.monitor` (as @aptiko noted) is incorrect and `celery.workers` is more appropriate. 

Now, on the issue. The error is produced due to the fact that `send_notification` depends on the execution of another management command `runswb` (which calculates swb model results for all database agrifields). As sequence, if for an agrifield model calculations haven't completed, the return result of `email_users_response_data(agrifield)` is `None` and breaks `sent_notification`. `None` result is also returned then an agrifield location is outside `aira.study_area`.

**Comment by kickapoo** [comment]
For the history of this issue, a list of commis exists:
1. 99d72ddc893ffceec5cb468f47d05e6657f54631
2. bf893f425df7a86dea7df4b64999caa2bb48b964
3. 2a753b8b1cd43a3e36f4fdf19d38b72370218a07
4. 7907e7759ecc1a6587ef1891640a67eae4991c6b
5. 67f837944195eb5d08063f6b0f2c46f2795737ac
6. dc3b3bd584ab00b829aee4b8c728abffbc3ab4a3
