### ISSUE TITLE
ValueError: could not broadcast input array from shape (60) into shape (59)

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#238]
This error occurs in celery in many fields, e.g. in the one with id=8.

```
Traceback (most recent call last):
  File "/opt/aira/venv/lib/python3.5/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/aira/venv/lib/python3.5/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/aira/aira/tasks.py", line 10, in calculate_agrifield
    agrifield.execute_model()
  File "/opt/aira/aira/agrifield.py", line 175, in execute_model
    self.prepare_timeseries()
  File "/opt/aira/aira/agrifield.py", line 105, in prepare_timeseries
    self._determine_crop_evapotranspiration()
  File "/opt/aira/aira/agrifield.py", line 95, in _determine_crop_evapotranspiration
    late=self.crop_type.days_kc_late,
  File "/opt/aira/venv/lib/python3.5/site-packages/swb/crop_evapotranspiration.py", line 8, in calculate_crop_evapotranspiration
    model.calculate()
  File "/opt/aira/venv/lib/python3.5/site-packages/swb/crop_evapotranspiration.py", line 22, in calculate
    self._calculate_kc_for_late_stage()
  File "/opt/aira/venv/lib/python3.5/site-packages/swb/crop_evapotranspiration.py", line 55, in _calculate_kc_for_late_stage
    self.timeseries.loc[start:end, "kc"] = late_kcs
  File "/opt/aira/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 202, in __setitem__
    self._setitem_with_indexer(indexer, value)
  File "/opt/aira/venv/lib/python3.5/site-packages/pandas/core/indexing.py", line 579, in _setitem_with_indexer
    self.obj._data = self.obj._data.setitem(indexer=indexer, value=value)
  File "/opt/aira/venv/lib/python3.5/site-packages/pandas/core/internals/managers.py", line 560, in setitem
    return self.apply("setitem", **kwargs)
  File "/opt/aira/venv/lib/python3.5/site-packages/pandas/core/internals/managers.py", line 438, in apply
    applied = getattr(b, f)(**kwargs)
  File "/opt/aira/venv/lib/python3.5/site-packages/pandas/core/internals/blocks.py", line 938, in setitem
    values[indexer] = value
ValueError: could not broadcast input array from shape (60) into shape (59)
```

**Comment by aptiko** [comment]
This is not a problem in aira, but in the fact that the wrong rasters have been created. It may be an hspatial bug. Will open another ticket as soon as I determine it.
