### ISSUE TITLE
ZeroDivisionError while executing model for agrifield with p=1.0

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#278]
`Agrifield.objects.get(pk=87).execute_model()`

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/anthony/nosync/virtualenvs/aira/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/anthony/nosync/virtualenvs/aira/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/anthony/nosync/virtualenvs/aira/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/anthony/nosync/virtualenvs/aira/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/home/anthony/nosync/development/openmeteo/aira/aira/management/commands/runswb.py", line 13, in handle
    agrifield.execute_model()
  File "/home/anthony/nosync/development/openmeteo/aira/aira/agrifield.py", line 192, in execute_model
    self.run_swb_model_normally()
  File "/home/anthony/nosync/development/openmeteo/aira/aira/agrifield.py", line 139, in run_swb_model_normally
    d = self.run_swb_model()
  File "/home/anthony/nosync/development/openmeteo/aira/aira/agrifield.py", line 135, in run_swb_model
    mif=self.irrigation_optimizer,
  File "/home/anthony/nosync/virtualenvs/aira/lib/python3.7/site-packages/swb/swb.py", line 6, in calculate_soil_water
    model.calculate_timeseries()
  File "/home/anthony/nosync/virtualenvs/aira/lib/python3.7/site-packages/swb/swb.py", line 61, in calculate_timeseries
    ks = self.ks(dr_prev)
  File "/home/anthony/nosync/virtualenvs/aira/lib/python3.7/site-packages/swb/swb.py", line 89, in ks
    result = (self.taw - dr) / ((1 - self.p) * self.taw)
ZeroDivisionError: float division by zero
```

`p` should probably not be allowed to have the value 1.0—maybe 0.8 is the max, will discuss with @nmalamos.

**Comment by aptiko** [comment]
After conferencing with Nikos and Yannis, p shall be allowed to be up to 0.99.
