### ISSUE TITLE
IndexError when calculating fields on 15 March 00:11 EET

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#281]
```
Task id: eacc81ef-a0d2-4398-a93e-cb7244b40e7d

Traceback (most recent call last):
  File "/opt/aira/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/aira/venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/aira/aira/tasks.py", line 10, in calculate_agrifield
    agrifield.execute_model()
  File "/opt/aira/aira/agrifield.py", line 191, in execute_model
    self.prepare_timeseries()
  File "/opt/aira/aira/agrifield.py", line 118, in prepare_timeseries
    self._determine_evaporation()
  File "/opt/aira/aira/agrifield.py", line 71, in _determine_evaporation
    "evaporation"
  File "/opt/aira/aira/agrifield.py", line 59, in _get_timeseries_from_rasters
    self.historical_end_date = historical.data.index[-1]
  File "/opt/aira/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3930, in __getitem__
    return getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by aptiko** [comment]
Same thing on 16 March 00:04.

**Comment by aptiko** [comment]
Apparently this was an error in the updating of the data. There had been no data for two days. Meanwhile the new irrigation season started, and there was no data for the new irrigation season because of the interruption in getting data. When it tries to execute the swb model and there's zero data, it crashes. This _is_ a bug, but it's really an edge case and we won't fix it at this stage.
