### ISSUE TITLE
Two tests failing with swb==1.0.2

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#292]

**Comment by aptiko** [comment]
```
======================================================================
FAIL: test_dr (aira.tests.test_agrifield.ExecuteModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anthony/nosync/development/openmeteo/aira/aira/tests/test_agrifield.py", line 211, in test_dr
    places=4,
AssertionError: 8.82197401705323 != 9.0148428 within 4 places (0.19286878294676946 difference)
======================================================================
FAIL: test_theta (aira.tests.test_agrifield.ExecuteModelTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/anthony/nosync/development/openmeteo/aira/aira/tests/test_agrifield.py", line 216, in test_theta
    self.timeseries.at[pd.Timestamp("2018-03-18 23:59"), "theta"], 0.3905107
AssertionError: 0.39071371752146106 != 0.3905107 within 7 places (0.00020301752146106855 difference)
```

Nikos Malamos implements the models in an Excel file and in order to verify that our code works correctly we cross-check the code's results with the Excel's results. He checked and it turns out that the correct results are indeed those calculated by the code, i.e. 8.82197 and 0.3907137. So we just need to modify the expected result in these unit tests (and set `swb>=1.0.2,<2` in `requirements.txt`).

Fix this before continuing with #291, otherwise Travis automated tests will fail.
