### ISSUE TITLE
IndexError: index -1 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#417]
```Traceback (most recent call last):
  File "/opt/aira-irma/venv/lib/python3.7/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/aira-irma/venv/lib/python3.7/site-packages/celery/app/trace.py", line 650, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/aira-irma/aira/tasks.py", line 18, in calculate_agrifield
    agrifield.execute_model()
  File "/opt/aira-irma/aira/agrifield.py", line 198, in execute_model
    self.prepare_timeseries()
  File "/opt/aira-irma/aira/agrifield.py", line 119, in prepare_timeseries
    self._determine_evaporation()
  File "/opt/aira-irma/aira/agrifield.py", line 65, in _determine_evaporation
    "evaporation"
  File "/opt/aira-irma/aira/agrifield.py", line 53, in _get_timeseries_from_rasters
    self.historical_end_date = historical.data.index[-1]
  File "/opt/aira-irma/venv/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 3929, in __getitem__
    return getitem(key)
IndexError: index -1 is out of bounds for axis 0 with size 0
```

**Comment by aptiko** [comment]
This occurs the first day of the irrigation period.
