### ISSUE TITLE
TypeError: can only concatenate str (not "float") to str

### ISSUE THREAD

**Issue by aptiko** [openmeteo/aira#440]
```
Traceback (most recent call last):
  File "/opt/aira-poros/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/aira-poros/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/aira-poros/aira/aira/tasks.py", line 19, in calculate_agrifield
    agrifield.execute_model()
  File "/opt/aira-poros/aira/aira/agrifield.py", line 198, in execute_model
    self.prepare_timeseries()
  File "/opt/aira-poros/aira/aira/agrifield.py", line 123, in prepare_timeseries
    self._determine_irrigation()
  File "/opt/aira-poros/aira/aira/agrifield.py", line 103, in _determine_irrigation
    applied_water_mm * self.irrigation_efficiency
TypeError: can only concatenate str (not "float") to str
```

Apparently this happens when there are two (or more) irrigations in a day, with one having a volume and the other one not.

**Comment by aptiko** [comment]
The easiest solution is to ignore the one with volume. However the "irrigation report" "latest irrigation" field will be confusing in that case if the last one is with volume. Maybe it's not worth fixing the confusion.
